#%RAML 1.0
title: "Javad Bucket"
version: ""
baseUri: "https://api.example.com/apis/xyz/pet/v1"
mediaType: "application/json"

/pet_describe:
  get:
    description: successful response
    responses:
      200:
        description: successful response
